
package my.troubleshoot;

import static java.awt.AWTEventMulticaster.add;
import static java.awt.Color.WHITE;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JTextArea;
import javax.swing.text.Document;



/**
 *
 * @author joshuamalloy from JoMa Interactive
 * Network Connectivity Troubleshooting Series 0.17*/
public class troubleshootUI extends javax.swing.JFrame {
    
//Global Variables  
    private final ImageIcon image1 = new ImageIcon(getClass().getResource("image1.png"));
    private boolean switchsEnd = false;
    private int cout = 0;
    private boolean routerEnd = false;
    private boolean serverEnd = false;
    private boolean otherEnd = false;
    private boolean computerEnd = false;
    private boolean wifiEnd = false;
    private boolean references = false;
    private boolean rule = true; 
    private boolean reset = false;
    private boolean save = false;
    private boolean switchs = false;
    private boolean router = false;
    private boolean server = false;
    private boolean other = false;
    private boolean computer = false;
    private boolean wifi = false;
    private boolean train = false;
    private boolean autoDisplay = false;
    private boolean yes = false;
    private boolean no = false;
    private boolean add = false;
    private boolean saveComputer = false;
    private boolean saveSwitch = false;
    private boolean saveRouter = false;
    private boolean saveWired = false;
    private boolean saveWifi = false;
    private boolean saveServer = false;
    private boolean saveOther = false;
    private boolean firstTimeComputer = true;
    private  FileInputStream instream = null;
    private  FileOutputStream outstream = null;
    private int counterC = 2;
    private int counterR = 2;
    private int countC = 3;
    private int countR = 3; 
    private int computerSize = 0;
    private int routerSize = 0;
    private int serverSize = 0;
    private int switchSize = 0;
    private int otherSize = 0;
    private int wifiSize = 0;
    private int referenceSize = 0;
    private int theCounterC = 2;
    private int theCounterR = 2;
    private int theCounterS = 2;
    private int theCounterSw = 2;
    private int theCounterO = 2;
    private int theCounterW = 2;
    private int theCounterRef = 2;
    private final String computerShoot = "";
    private final String routerShoot = "";
    private final String otherShoot = "";
    private final String switchShoot = "";
    private final String serverShoot = "";
    private final String pcString = "";
    private final String routerString = "";
    private final String hlp = " Help Desk";
    private final String tech = " Tech Support";
    private final String admin = " Administration Support";
    private final String ven = " Vendor Support";
    private String stringEnter = "";
    private String text = "";  
    private File source;
    private File dest;
    private final ArrayList<String> listRef = new ArrayList<String> ();
    private final ArrayList<String> listpc = new ArrayList<String> ();
    private final ArrayList<String> listR = new ArrayList<> ();
    private final ArrayList<String> listSw = new ArrayList<> ();
    private final ArrayList<String> listS = new ArrayList<> ();
    private final ArrayList<String> listO = new ArrayList<> ();
    private final ArrayList<String> listW = new ArrayList<> ();
    private final Font font = new Font("Courier", Font.BOLD,14);
    public troubleshootUI() {
       initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        textArea = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        question = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        Rules = new javax.swing.JButton();
        Switch = new javax.swing.JButton();
        Wifi = new javax.swing.JButton();
        Wired = new javax.swing.JButton();
        Router = new javax.swing.JButton();
        Server = new javax.swing.JButton();
        Other = new javax.swing.JButton();
        Training = new javax.swing.JButton();
        References = new javax.swing.JButton();
        help = new javax.swing.JButton();
        level = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Noteworthy", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/troubleshoot/netWorkPic.png"))); // NOI18N

        exitButton.setForeground(new java.awt.Color(0, 51, 204));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonButton(evt);
            }
        });

        addButton.setForeground(new java.awt.Color(0, 51, 255));
        addButton.setLabel("Add ");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonButton(evt);
            }
        });

        textArea1.setEditable(false);
        textArea1.setColumns(20);
        textArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textArea1.setRows(5);
        textArea1.setText("Rules:\n\nHow many people will be effected by change?\n\nWill data be effected?\n\nWho needs to be involved?\n\nDoes management need to be involved?\n\nDoes other members of the team need to be involved?\n\nDoes vendor(s) need to be involved?\n\nIs it software or hardware?\n\nWhat procedure do I need to do?\n\n");
        textArea1.setLineWrap(true);
        textArea.setViewportView(textArea1);
        textArea1.setWrapStyleWord(true);

        question.setBackground(new java.awt.Color(0, 0, 0));
        question.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        question.setForeground(new java.awt.Color(255, 255, 255));
        question.setOpaque(true);

        saveButton.setForeground(new java.awt.Color(0, 51, 255));
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonButton(evt);
            }
        });

        resetButton.setForeground(new java.awt.Color(0, 51, 204));
        resetButton.setText("Reset ");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton(evt);
            }
        });

        yesButton.setForeground(new java.awt.Color(0, 51, 204));
        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButton(evt);
            }
        });

        noButton.setForeground(new java.awt.Color(0, 51, 204));
        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("Luminari", 3, 13)); // NOI18N

        Rules.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        Rules.setText("Rules");
        buttonGroup1.add(Rules);
        Rules.setMaximumSize(new java.awt.Dimension(97, 19));
        Rules.setMinimumSize(new java.awt.Dimension(97, 19));
        Rules.setPreferredSize(new java.awt.Dimension(97, 19));
        Rules.setSelected(true);
        Rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesActionPerformed(evt);
            }
        });
        jToolBar1.add(Rules);
        Rules.getAccessibleContext().setAccessibleName("rulesTab");

        Switch.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        buttonGroup1.add(Switch);
        Switch.setLabel("Switch");
        Switch.setMaximumSize(new java.awt.Dimension(97, 19));
        Switch.setMinimumSize(new java.awt.Dimension(97, 19));
        Switch.setPreferredSize(new java.awt.Dimension(97, 19));
        Switch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitchActionPerformed(evt);
            }
        });
        jToolBar1.add(Switch);
        Switch.getAccessibleContext().setAccessibleName("switchTab");

        Wifi.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        Wifi.setText("Wifi Computer");
        buttonGroup1.add(Wifi);
        Wifi.setMaximumSize(new java.awt.Dimension(97, 19));
        Wifi.setMinimumSize(new java.awt.Dimension(97, 19));
        Wifi.setPreferredSize(new java.awt.Dimension(97, 19));
        Wifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WifiActionPerformed(evt);
            }
        });
        jToolBar1.add(Wifi);
        Wifi.getAccessibleContext().setAccessibleName("wifiTab");

        Wired.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        buttonGroup1.add(Wired);
        Wired.setLabel("Wired Computer");
        Wired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WiredActionPerformed(evt);
            }
        });
        jToolBar1.add(Wired);
        Wired.getAccessibleContext().setAccessibleName("wiredTab");

        Router.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        Router.setText("Router");
        buttonGroup1.add(Router);
        Router.setMaximumSize(new java.awt.Dimension(97, 19));
        Router.setMinimumSize(new java.awt.Dimension(97, 19));
        Router.setPreferredSize(new java.awt.Dimension(97, 19));
        Router.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouterActionPerformed(evt);
            }
        });
        jToolBar1.add(Router);
        Router.getAccessibleContext().setAccessibleName("routerTab");

        Server.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        Server.setText("Server");
        buttonGroup1.add(Server);
        Server.setMaximumSize(new java.awt.Dimension(97, 19));
        Server.setMinimumSize(new java.awt.Dimension(97, 19));
        Server.setPreferredSize(new java.awt.Dimension(97, 19));
        Server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerActionPerformed(evt);
            }
        });
        jToolBar1.add(Server);
        Server.getAccessibleContext().setAccessibleName("serverTab");

        Other.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        buttonGroup2.add(Other);
        Other.setFocusCycleRoot(true);
        Other.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Other.setLabel("Other");
        Other.setMaximumSize(new java.awt.Dimension(97, 19));
        Other.setMinimumSize(new java.awt.Dimension(97, 19));
        Other.setPreferredSize(new java.awt.Dimension(97, 19));
        Other.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherActionPerformed(evt);
            }
        });
        jToolBar1.add(Other);
        Other.getAccessibleContext().setAccessibleName("otherTab");

        Training.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        Training.setText("Training");
        buttonGroup1.add(Training);
        Training.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Training.setMaximumSize(new java.awt.Dimension(97, 19));
        Training.setMinimumSize(new java.awt.Dimension(97, 19));
        Training.setName(""); // NOI18N
        Training.setOpaque(true);
        Training.setPreferredSize(new java.awt.Dimension(97, 19));
        Training.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Training.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainingActionPerformed(evt);
            }
        });
        jToolBar1.add(Training);
        Training.getAccessibleContext().setAccessibleName("trainingTab");

        References.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        References.setText("References");
        buttonGroup1.add(References);
        References.setMaximumSize(new java.awt.Dimension(97, 19));
        References.setMinimumSize(new java.awt.Dimension(97, 19));
        References.setPreferredSize(new java.awt.Dimension(97, 19));
        References.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReferencesActionPerformed(evt);
            }
        });
        jToolBar1.add(References);
        References.getAccessibleContext().setAccessibleName("refTab");

        help.setFont(new java.awt.Font("Luminari", 3, 11)); // NOI18N
        help.setText("Help");
        buttonGroup1.add(help);
        help.setFocusable(false);
        help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        help.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jToolBar1.add(help);

        level.setBackground(new java.awt.Color(0, 0, 0));
        level.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setOpaque(true);

        jButton10.setForeground(new java.awt.Color(0, 0, 255));
        jButton10.setText("Command");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(level, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jButton10)
                                .addGap(52, 52, 52)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton10)
                                .addComponent(resetButton)
                                .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yesButton)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        jButton10.getAccessibleContext().setAccessibleName("cmdPrompt");

        pack();
    }// </editor-fold>//GEN-END:initComponents

/*This will be used to get the Command Prompt or Terminal*/    
    private void getProgram(String programName)
    {
        Runtime runtime = Runtime.getRuntime();     
        try
        {
            runtime.exec(programName);        
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
    }// End of Get Program
    private void exitButtonButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonButton
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonButton
// Add Button
    private void addButtonButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonButton
System.out.println(switchs + " 493");
        add = true;
        reset = false;
        save = false;
        addButton.setEnabled(false);
        resetButton.setEnabled(false);
        saveButton.setEnabled(true);
       if(rule || train)
       {
          question.setText(" Can not edit this section! ");
          this.add = false;
       }
       else
       {
            textArea1.setText(" ");
            this.add = true;
            question.setText(" Are you sure you want to add to file? ");
       }    
    }//GEN-LAST:event_addButtonButton
// Save Button
    private void saveButtonButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonButton
System.out.println(switchs + " 514");
        textArea1.setEditable(false);
        addButton.setEnabled(false);
        resetButton.setEnabled(false);
        saveButton.setEnabled(false);
        exitButton.setEnabled(true);
        question.setText(" Are you ready to save?");
        stringEnter = textArea1.getText();
        save = true;
        add = false;
        reset = false;
        if(switchs)
        {
            //saveSwitch = false;
            theCounterC++;
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_saveButtonButton
// yes button not done
    private void yesButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButton
// if user fines what they are looking for
        if(!add && !train && !rule && !save && !reset && !references)
            question.setText(" Glad to be helpful.");  
   if(add)
         {
// This allows user to type in textArea
            textArea1.setEditable(true);

    /***********************Reads in wired Computer information*******************/    
            if(computer)
               {
                    readIn("Computer.txt");
                    if(theCounterC <= computerSize)
                        theCounterC++;

                    else
                        theCounterC = computerSize;
               }
    /***********************Reads in Wifi information*******************/    
            else if(wifi)
            {
                readIn("wifi.txt");
                if(theCounterW<= wifiSize)
                    theCounterW++;

                else
                    theCounterW = wifiSize;
            }
    /***********************Reads in Router information*******************/  
            else if(router)
               {   
                    readIn("router.txt");
                    if(theCounterR <= routerSize)
                        theCounterR++;

                    else
                        theCounterR = routerSize;
               }
    /***********************Reads in Switch information*******************/  
            else if(switchs)
               {
                    readIn("switch.txt");
                                
                    if(theCounterSw <= switchSize)
                        theCounterSw++;

                    else
                        theCounterSw = switchSize;
               }
    /***********************Reads in Server information*******************/  
            else if(server)
               {
                    readIn("server.txt");
                    if(theCounterS <= serverSize)
                        theCounterS++;

                    else
                        theCounterS = serverSize;
               }
    /***********************Reads in Other information*******************/  
            else if(other)
               {
                    readIn("other.txt");
                    if(theCounterO <= otherSize)
                        theCounterO++;

                    else
                        theCounterO = otherSize;
               }
    /***********************Reads in References information*******************/  
            else if(references)
               {
                    readIn("references.txt");
                    if(theCounterRef <= referenceSize)
                        theCounterRef++;

                    else
                        theCounterRef = referenceSize;
               }
/************************Tells user what to do to ***************************/
           question.setText(" Type in the area below to add dont hit enter unless adding more than one step."); 
                   

         }
 /*************************If users is saving file************************/        
         if(save)
         {
/*************************Resting textArea to not editable question to nothing and save to be disabled**/
             question.setText("");
 /************************* fines which section is to be save at *************/                   
             if(switchs)
                saveSwitch = true;
             if(other)
                saveOther = true;
             if(wifi)
                saveWifi = true;
             if(router)
                saveRouter = true;
             if(server)
                saveServer = true;
             if(computer)
                saveWired = true;
/************************This calls add to file which adds the text to the file*****/
             if(!reset)
             {
                try
                {
                    addToFile();
System.out.println(switchs + "643");
                } 
                catch (IOException ex)
                {
                    Logger.getLogger(troubleshootUI.class.getName()).log(Level.SEVERE, null, ex);
                }
             } // ends if
         }// ends save
/**************************This calls reset if user wants to set back to default settings ****/

    if(reset)
    {
/******************************Rests Switch file***************/
        if(switchs)
        {
             readIn("switch.txt");
 System.out.println("save me 653");   
            //FileInputStream instream = null;
            /*FileOutputStream outstream = null;
            try
            {
                File infile = new File("defaultSwitch.txt");
                File outFile = new File("switch.txt");

                instream = new FileInputStream(infile);
                outstream = new FileOutputStream(outFile);

                byte [] buffer = new byte [1024];
                int length;

                while( (length = instream.read(buffer)) > 0) 
                {
                    outstream.write(buffer, 0, length);
                }// ends while
                instream.close();
                outstream.close();             
            }// ends try
            catch(IOException ioe)
            {
            }// ends catch  */
           // source = new File("defaultSwitch.txt");
            //dest = new File("switch.txt");
            try (FileReader fr = new FileReader("defaultSwitch.txt");
            FileWriter fw = new FileWriter("switch.txt");) {
            int c = fr.read();
            while(c!=-1) {
                fw.write(c);
                c = fr.read();
            }
        } catch(IOException e) {
            e.printStackTrace();
        }


           
        }//ends if

/********************Ends the Switch********************/
/******************************Rests wifi file***************/
        if(wifi)
        {
            FileInputStream instream = null;
            FileOutputStream outstream = null;
            try
            {
                File infile = new File("defaultWifi.txt");
                File outFile = new File("wifi.txt");

                instream = new FileInputStream(infile);
                outstream = new FileOutputStream(outFile);

                byte [] buffer = new byte [1024];
                int length;

                while( (length = instream.read(buffer)) > 0) 
                {
                    outstream.write(buffer, 0, length);
                }// ends while
                instream.close();
                outstream.close();             
            }// ends try
            catch(IOException ioe)
            {
            }// ends catch  
            readIn("wifi.txt");
        }//ends wifi
/********************Ends the wifi********************/
          

    }// ends loop

        if(save)
        {
            addButton.setEnabled(true);
            saveButton.setEnabled(false);
            resetButton.setEnabled(true);
            exitButton.setEnabled(true);
        }
        if(reset)
        {
            readIn("switch.txt");
            addButton.setEnabled(true);
            saveButton.setEnabled(false);
            resetButton.setEnabled(true);
            exitButton.setEnabled(true);
        }
    }//GEN-LAST:event_yesButton
//No button
    private void noButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButton
    // Variables ==================================
        no = true;   
        autoDisplay = false;     
/***********************Computer*******************/    
    if(computer && !computerEnd)
       {
            if(theCounterC < computerSize)
                theCounterC++;
            else
                theCounterC = computerSize;
            readIn("Computer.txt");
       }
/***********************Computer*******************/    
    if(wifi && !wifiEnd)
       {
   
            if(theCounterW < wifiSize)
                theCounterW++;
            else
                theCounterW = wifiSize;
            readIn("wifi.txt");
       }
/***********************Router*******************/  
       if(router && !routerEnd)
       {   
            if(theCounterR < routerSize)
                theCounterR++;
            else
                theCounterR = routerSize;
            readIn("router.txt");
       }
/***********************Switch*******************/  
       if(switchs && !switchsEnd)
       {
            readIn("switch.txt");
            if(theCounterSw <= switchSize)
                theCounterSw++;

            else
                theCounterSw = switchSize;
       }
/***********************Server*******************/  
       if(server && !serverEnd)
       {
            if(theCounterS < serverSize)
                theCounterS++;
            else
                theCounterS = serverSize;
            readIn("server.txt");
       }
/***********************Other*******************/  
       if(other && !serverEnd)
       {
            if(theCounterO < otherSize)
                theCounterO++;
            else
                theCounterO = otherSize;
            readIn("other.txt");
       }

    }//GEN-LAST:event_noButton
// Reset button not finished yet
    private void resetButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton
        addButton.setEnabled(false);
        resetButton.setEnabled(false);
        saveButton.setEnabled(false);
        reset = true;     
        save = false;
        add = false;
        if(switchs)
            question.setText(" Are you sure you want to reset switch section back to default? ");
        if(wifi)
            question.setText(" Are you sure you want to reset wifi section back to default? ");
        if(computer)
            question.setText(" Are you sure you want to reset wired computer section back to default? ");
        if(other)
            question.setText(" Are you sure you want to reset other section back to default? ");
        if(router)
            question.setText(" Are you sure you want to reset router section back to default? ");
        if(server)
            question.setText(" Are you sure you want to reset server section back to default? ");
    }//GEN-LAST:event_resetButton
//Switch Button
    private void SwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitchActionPerformed
        this.rule = false;
        this.switchs = true;
        this.router = false;
        this.server = false;
        this.other = false;
        this.computer = false;
        this.wifi = false;
        this.train = false;
        this.references = false;
        readIn("switch.txt"); // TODO add your handling code here:
    }//GEN-LAST:event_SwitchActionPerformed
// Rule Button
    private void RulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesActionPerformed
       this.rule = true;
       this.switchs = false;
       this.router = false;
       this.server = false;
       this.other = false;
       this.computer = false;
       this.wifi = false;
       this.train = false;
       this.references = false;
       question.setText("");
       level.setText("");
       textArea1.setText("");
       textArea1.setText("\nRules:\n" 
                         + "\nHow many people will be effected by change?\n"
                         + "\nWill data be effected?\n"
                         + "\nWho needs to be involved?\n"
                         + "\nDoes management need to be involved?\n"
                         + "\nDoes other members of the team need to be involved?\n"
                         + "\nDoes vendor(s) need to be involved?\n"
                         + "\nIs it software or hardware?\n" 
                         + "\nWhat procedure do I need to do?");        // TODO add your handling code here:
    }//GEN-LAST:event_RulesActionPerformed
// Other Button
    private void OtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherActionPerformed
       this.rule = false;
       this.switchs = false;
       this.router = false;
       this.server = false;
       this.other = true;
       this.computer = false;
       this.wifi = false;
       this.train = false;
       this.references = false;
       readIn("other.txt");        // TODO add your handling code here:
    }//GEN-LAST:event_OtherActionPerformed
//Wifi Button
    private void WifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WifiActionPerformed
       this.rule = false;
       this.switchs = false;
       this.router = false;
       this.server = false;
       this.other = false;
       this.wifi = true;
       this.computer = false;
       this.train = false;
       this.references = false;
       readIn("wifi.txt");         // TODO add your handling code here:
    }//GEN-LAST:event_WifiActionPerformed
// Wired Button
    private void WiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WiredActionPerformed
    //Variables      
       this.rule = false;
       this.switchs = false;
       this.router = false;
       this.server = false;
       this.other = false;
       this.wifi = false;
       this.computer = true;
       this.train = false;
       this.add = false;
       this.references = false;
       readIn("Computer.txt");           // TODO add your handling code here:
    }//GEN-LAST:event_WiredActionPerformed
// Router button
    private void RouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouterActionPerformed
       this.rule = false;
       this.switchs = false;
       this.router = true;
       this.server = false;
       this.other = false;
       this.computer = false; 
       this.wifi = false;
       this.train = false;
       this.references = false;
       readIn("router.txt");        // TODO add your handling code here:
    }//GEN-LAST:event_RouterActionPerformed
// server
    private void ServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerActionPerformed
       this.rule = false;
       this.switchs = false;
       this.router = false;
       this.server = true;
       this.other = false;
       this.computer = false;
       this.wifi = false;
       this.train = false;
      readIn("server.txt");        // TODO add your handling code here:
    }//GEN-LAST:event_ServerActionPerformed
// traing Button
    private void TrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainingActionPerformed
       this.rule = false;
       this.switchs = false;
       this.router = false;
       this.server = false;
       this.other = false;
       this.computer = false;
       this.wifi = false;
       this.train = true;
       this.references = false;
        question.setText(" ");
        textArea1.setText("\nTraining Process:\n" 
                         + "\nRead and take a quiz on confidentiality.\n"
                         + "\nBe introduced to the fellow workers if you haven't already met.\n"
                         + "\nUnderstanding of the working enviroment, such as proper outfit.\n"
                         + "\nSitting in on a weekly conference call.\n"
                         + "\nLearn the proper protocol that needs to be done before doing major changes.\n"
                         + "\nLearn how to fill out the paper that is needed.\n"
                         + "\nLearning the software that is being used: Orion, Prime, and Putty.\n"
                         + "\nCreate a small network in lab to show your understand of how a network works with WLAN.\n"
                         + "\nIncrease knowledge of other parts of IT that you might not normal have to do.\n"
                         + "\nLearn the steps to do an audit on servers.\n" 
                         + "\nBeing able to resolve application issues.\n"
                         + "\n");        // TODO add your handling code here:
    }//GEN-LAST:event_TrainingActionPerformed
// References Button
    private void ReferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReferencesActionPerformed
        this.rule = false;
        this.switchs = false;
        this.router = false;
        this.server = false;
        this.other = false;
        this.computer = false;
        this.wifi = false;
        this.train = false;
        this.references = true;
        question.setText("");
        level.setText("");
        readIn("references.txt");
        
    }//GEN-LAST:event_ReferencesActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        new helpDesk().setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
       this.rule = true;
       this.switchs = false;
       this.router = false;
       this.server = false;
       this.other = false;
       this.computer = false;
       this.wifi = false;
       this.train = false;
       this.references = false;
       level.setText("");
       question.setText(" ");
       

    }//GEN-LAST:event_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new troubleshootUI().setVisible(true);
                
            }
        });
    }
 // This Section reads in whatever file that the user is looking at 
    private void readIn(String filename)
    {
  System.out.println(add + " 1004");
/**************Variables ****************/
       //ArrayList <String> listComputer = new ArrayList <String> (); 
       textArea1.setText("");    
       String input = "";
       String textFieldReadable = "";
       String tfr = "";
       computerSize = 0;
       routerSize = 0;
       serverSize = 0;
       otherSize = 0;
       switchSize = 0;
       wifiSize = 0;
       referenceSize = 0;
/***************Try to catch the file trying to open**************/
       try {
            FileReader fileReader = new FileReader(new File(filename).getAbsolutePath());
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            textFieldReadable = bufferedReader.readLine();
            while (textFieldReadable != null){
                textFieldReadable = bufferedReader.readLine();
                
                if(!(textFieldReadable == (null)))
                {  
/****************************Puts file in the proper list...******************/
                    tfr = textFieldReadable;
                    if(computer)
                        listpc.add(tfr); 
                    if(router)
                        listR.add(tfr);
                    if(server)
                        listS.add(tfr);
                    if(switchs)
                        listSw.add(tfr);
                    if(other)
                        listO.add(tfr);
                    if(wifi)
                        listW.add(tfr);
                    if(references)
                        listRef.add(tfr);
                }
                
/***********************Gets how big the file is...*************************/
                if(computer)
                    computerSize++;
                if(router)
                    routerSize++;
                if(server)
                    serverSize++;
                if(switchs)
                    switchSize++;
                if(other)
                    otherSize++;
                if(wifi)
                    wifiSize++;
                if(references)
                    referenceSize++;
                
            }// ends while
            
        }// ends try
      
        catch (FileNotFoundException ex) {
             System.out.println("no such file exists");
             textArea1.setText("no such file exists");
        } // ends catch 
        catch (IOException ex) {
            System.out.println("unkownerror");
        } // ends catch

       if(!add)
       {
         printOut();
       }
       //else
       //   question.setText(" Do you want to save? ");
    }
 
    
    /******************************This adds new data to files*/
    private void addToFile() throws IOException
    {   
      String temp = "";
 /*************************writes to Computer.txt*********/
        if(computer)
        {   
            FileWriter writer = new FileWriter("Computer.txt"); 
            for(int j = 0; j < computerSize -1; j ++)
            {
                    if( j < computerSize)
                    {
                         temp = listpc.get(j);
                         writer.write("\n" + temp);
                    }
            }
           
            writer.write("\n" + stringEnter);      
            writer.close();
            listpc.clear();
            readIn("Computer.txt");
        }
/****************************writes to wifi.txt*********/
        else if(wifi)
        {
            FileWriter writer = new FileWriter("wifi.txt"); 
            for(int j = 0; j < wifiSize -1; j ++)
            {
                    if( j < wifiSize)
                    {
                         temp = listW.get(j);
                         writer.write("\n" + temp);
                    }
            }
           
            writer.write("\n" + stringEnter);      
            writer.close();
            listW.clear();
            readIn("wifi.txt");
        }  
/****************************writes to router.txt*********/
        else if(router)
        {
            FileWriter writer = new FileWriter("router.txt"); 
            for(int j = 0; j < routerSize -1; j ++)
            {
                    if( j < routerSize)
                    {
                         temp = listR.get(j);
                         writer.write("\n" + temp);
                    }
            }
           
            writer.write("\n" + stringEnter);      
            writer.close();
            listR.clear();
            readIn("router.txt");
        }  
/****************************writes to switch.txt*********/
        if(switchs)
        {
            int num = switchSize - 1;

            FileWriter writer = new FileWriter("switch.txt"); 
            for(int j = 0; j < num; j ++)
            {
                    if( j < switchSize)
                    {
                         temp = listSw.get(j);
                         writer.write("\n" + temp);
                    }
            }
           
            writer.write("\n" + stringEnter);      
            writer.close();
            listSw.clear();
            readIn("switch.txt");

        }
/****************************writes to other.txt*********/
        else if(other)
        {
            FileWriter writer = new FileWriter("other.txt"); 
            for(int j = 0; j < otherSize -1; j ++)
            {
                    if( j < otherSize)
                    {
                         temp = listO.get(j);
                         writer.write("\n" + temp);
                    }
            }
           
            writer.write("\n" + stringEnter);      
            writer.close();
            listO.clear();
            readIn("other.txt");
        } 
/****************************writes to server.txt*********/
        else if(server)
        {
            FileWriter writer = new FileWriter("server.txt"); 
            for(int j = 0; j < serverSize -1; j ++)
            {
                    if( j < serverSize)
                    {
                         temp = listS.get(j);
                         writer.write("\n" + temp);
                    }
            }
           
            writer.write("\n" + stringEnter);      
            writer.close();
            listS.clear();
            readIn("server.txt");           
        } 
 /*************************writes to References.txt*********/
        else if(references)
        {
            FileWriter writer = new FileWriter("references.txt"); 
            for(int j = 0; j < referenceSize -1; j ++)
            {
                    if( j < referenceSize)
                    {
                         temp = listRef.get(j);
                         writer.write("\n" + temp);
                    }
            }
           
            writer.write("\n" + stringEnter);      
            writer.close();
            listRef.clear();
            readIn("references.txt");
 
        }    
        stringEnter = "";
    }
 /********************************Prints to text area**********/
    private void printOut()
    {     
/******************Variables*************************************/
        int size = 0; 
        boolean noMore = false;
        int printCount = 0;

        text = "";
        if(computer)
        {
            size = computerSize;
            printCount = theCounterC;  
        }
        if(router)
        {
            size = routerSize;
            printCount = theCounterR;         
        }
        if(switchs)
        {
            size = switchSize;
            printCount = theCounterSw; 
            
        }    
        if(other)
        {
            size = otherSize;
            printCount = theCounterO;
           
        }
        if(server)
        {
            size = serverSize;
            printCount = theCounterS;         
        }
        if(wifi)
        {
            size = wifiSize;
            printCount = theCounterW;         
        }
        if(references)
        {
            size = referenceSize;
            printCount = theCounterRef;         
        }
        if(printCount <= size )
        {
            if(printCount == size)
            {
                printCount--;
                noMore = true;
            }
 
 //************************Displays Computer wired ****************************
              if(computer)
              {
                for(int i = 0; i < listpc.size(); i ++){
                    if(printCount > i)    
                    {
             
                      if(i < 1)
                        text = text + "\n" + listpc.get(i) + "\n";  
                      else
                        text = text + "\n" + (i) +") " + listpc.get(i) + "\n"; 

                      if(!saveWired)  
                       {
                          if(printCount > i)
                              question.setText(" Did Step " + (i) + " work?");

                          if(noMore)
                          {
                              question.setText(" I used all my resources.");
                              computerEnd = true;
                          }
                       }   

                      if(saveWired)
                      {
                         if(save)
                            question.setText(" Your file was saved!");
                         else
                             question.setText(" All resources used up!");
                         level.setText( "");
                      }   
                     }
                   
                textArea1.setText(text);
                }// ends for loop
              }
//************************ End Of Computer **************************** 
 //************************Displays Computer wifi ****************************
              if(wifi)
              {
                  for(int i = 0; i < listW.size(); i++){
                      if(printCount > i)
                      {
                          
                          if(i < 1)
                              text = text + "\n" + listW.get(i) + "\n";
                          else
                              text = text + "\n" + (i) +") " + listW.get(i) + "\n";
                          
                          if(!saveWifi)
                          {
                              if(printCount > i)
                                  question.setText(" Did Step " + (i) + " work?");
                              
                              if(noMore)
                              {
                                  question.setText(" I used all my resources.");
                                  switchsEnd = true;
                              }
                          }
                          
                          if(saveWifi)
                          {
                              if(save)
                                  question.setText(" Your file was saved!");
                              else
                                  question.setText(" All resources used up!");
                              level.setText( "");
                          }
                      }
                  }
                  textArea1.setText(text);
            }
//************************ End Of Computer wifi **************************** 
//************************Displays Router****************************
              if(router)
              {
                for(int i = 0; i < listR.size(); i ++){
                    if(printCount > i)    
                    {
             
                      if(i < 1)
                        text = text + "\n" + listR.get(i) + "\n";  
                      else
                        text = text + "\n" + (i) +") " + listR.get(i) + "\n"; 

                      if(!saveRouter)  
                       {
                          if(printCount > i)
                              question.setText(" Did Step " + (i) + " work?");

                          if(noMore)
                          {
                              question.setText(" I used all my resources.");
                              routerEnd = true;
                          }
                       }   

                      if(saveRouter)
                      {
                         if(save)
                            question.setText(" Your file was saved!");
                         else
                             question.setText(" All resources used up!");
                         level.setText( "");
                      }   
                     }
                   
                textArea1.setText(text);
                }// ends for loop
              }
//**********************End Of Router*********************************
//************************Displays switches ****************************
 System.out.println(cout + " Display in printout 1389");
              if(switchs)
              {
cout++;
                for(int i = 0; i < listSw.size(); i++){
                    if(printCount > i)    
                    {
             
                      if(i < 1)
                        text = text + "\n" + listSw.get(i) + "\n";  
                      else
                        text = text + "\n" + (i) +") " + listSw.get(i) + "\n"; 

                      if(!saveSwitch)  
                       {
                          if(printCount > i)
                              question.setText(" Did Step " + (i) + " work?");

                          if(noMore)
                          {
                              question.setText(" I used all my resources.");
                              switchsEnd = true;
                          }
                       }   

                      if(saveSwitch)
                      {
                         if(save)
                            question.setText(" Your file was saved!");
                         else
                             question.setText(" All resources used up!");
                         level.setText( "");
                      }   
                     }
                   }
                textArea1.setText(text);
              }
//************************End Switchesr****************************
//************************Displays Others****************************
              if(other)
              {
                for(int i = 0; i < listO.size(); i ++){
                    if(printCount > i)    
                    {
             
                      if(i < 1)
                        text = text + "\n" + listO.get(i) + "\n";  
                      else
                        text = text + "\n" + (i) +") " + listO.get(i) + "\n"; 

                      if(!saveOther)  
                       {
                          if(printCount > i)
                              question.setText(" Did Step " + (i) + " work?");

                          if(noMore)
                          {
                              question.setText(" I used all my resources.");
                              otherEnd = true;
                          }
                       }   

                      if(saveOther)
                      {
                         if(save)
                            question.setText(" Your file was saved!");
                         else
                             question.setText(" All resources used up!");
                         level.setText( "");
                      }   
                     }
                   
                textArea1.setText(text);
                }// ends loop
              }
//************************End of Others****************************
//************************Displays Servers****************************
              if(server)
              {
                for(int i = 0; i < listS.size(); i ++){
                    if(i < 1)                
                      text = text + "\n" + listS.get(i) + "\n";  
                    else
                      text = text + "\n" + (i) +") " + listS.get(i) + "\n"; 

                    if(!saveServer)  
                     {                   
                        if(printCount > i)
                            question.setText(" Did Step " + (i) + " work?");
                        if(noMore)
                        {
                            question.setText(" I used all my resources.");
                            serverEnd = true;
                        }
                     }
                     if(saveServer)
                     {
                         if(save)
                            question.setText(" Your file was saved!");
                         else
                             question.setText(" All resources used up!");
                         level.setText( "");
                     }
                }// ends loop
              }// ends server
//************************End of Servers****************************

//************************Displays References****************************
          if(references)  
          {
                for(int i = 0; i < listRef.size(); i ++)
                {
                  text = "";
                for(int j = 0; j < referenceSize -1; j ++)
                  {
                      text = text + listRef.get(j) + "\n";     
                  }
            }
          }// ends loop
                  textArea1.setText(text);

              if(noMore && references)
              {
               question.setText("");
              }               
          
          
//************************End of References****************************/
            
        }
    }
    /*This is the Reset Section that puts everything back to default */
        private void Reset() throws FileNotFoundException, IOException
        {
            FileInputStream instream = null;
            FileOutputStream outstream = null;
            
            if(switchs)
            {
                try{
                    File infile = new File("defaultSwitch.txt");
                    File outFile = new File("switch.txt");
                    
                    instream = new FileInputStream(infile);
                    outstream = new FileOutputStream(outFile);
                    
                    byte [] buffer = new byte [1024];
                    int length;
                    
                    while( (length = instream.read(buffer)) > 0) {
                        outstream.write(buffer, 0, length);
                    }
                    instream.close();
                    outstream.close();             
                }catch(IOException ioe){
                }

            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Other;
    private javax.swing.JButton References;
    private javax.swing.JButton Router;
    private javax.swing.JButton Rules;
    private javax.swing.JButton Server;
    private javax.swing.JButton Switch;
    private javax.swing.JButton Training;
    private javax.swing.JButton Wifi;
    private javax.swing.JButton Wired;
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton help;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel level;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel question;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane textArea;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
